"""
src/train/train.py

Config-driven training loop for the 8-way fetal plane classifier.

Usage:
    conda run -n fetalplane python -m src.train.train --config configs/repvgg_a1.yaml
    # or from repo root:
    conda run -n fetalplane python src/train/train.py --config configs/repvgg_a1.yaml

Design notes (cross-referenced against PHASE_4_KICKOFF_PROMPT.md):
- §4.1  Class weights loaded by explicit CANONICAL_CLASSES index order — never .values()
- §4.2  Uses FocalPlanesDataset + get_train_transform / get_eval_transform, parameterized
        by image_size from config so a per-backbone resolution can be specified.
- §4.3  AdamW + CosineAnnealingLR + torch.cuda.amp (GradScaler)
- §4.4  Macro-F1 is the early-stopping and model-selection metric (not accuracy).
        Per-class F1, precision, recall logged at every epoch to TensorBoard.
        Confusion matrix saved at best-checkpoint epoch and final epoch.
- §4.5  Saves best.pt + config YAML copy to checkpoints/<backbone_name>/
"""
from __future__ import annotations

import argparse
import json
import logging
import random
import shutil
import time
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

import numpy as np
import torch
import torch.nn as nn
import yaml
from sklearn.metrics import (
    classification_report,
    f1_score,
)

from src.eval.metrics_utils import save_confusion_matrix
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

from src.data.dataset import (
    CANONICAL_CLASSES,
    NUM_CLASSES,
    FocalPlanesDataset,
)
from src.data.transforms import get_eval_transform, get_train_transform
from src.models.backbone import build_model
from src.train.losses import FocalLoss

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_config(config_path: str) -> dict:  # type: ignore[type-arg]
    """Load a YAML config file into a plain dict."""
    with open(config_path) as f:
        cfg: dict = yaml.safe_load(f)  # type: ignore[assignment]
    return cfg


def build_class_weight_tensor(
    class_weights_json: str,
    device: torch.device,
) -> torch.Tensor:
    """Load class weights indexed explicitly by CANONICAL_CLASSES order.

    IMPORTANT (§4.1): We never call .values() on the dict because dict
    insertion order is fragile if the JSON is regenerated by different code.
    Explicit CANONICAL_CLASSES indexing is the only safe approach.
    """
    with open(class_weights_json) as f:
        raw_weights: dict[str, float] = json.load(f)

    # Validate that the JSON contains all expected keys
    missing = set(CANONICAL_CLASSES) - set(raw_weights.keys())
    if missing:
        raise ValueError(
            f"class_weights.json is missing keys: {missing}. "
            f"Expected all of: {CANONICAL_CLASSES}"
        )

    weights = torch.tensor(
        [raw_weights[cls] for cls in CANONICAL_CLASSES],
        dtype=torch.float32,
    ).to(device)
    return weights



# ---------------------------------------------------------------------------
# Training / validation passes
# ---------------------------------------------------------------------------

def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,  # type: ignore[type-arg]
    criterion: nn.Module,
    optimizer: AdamW,
    scaler: torch.amp.GradScaler,
    device: torch.device,
    epoch: int,
    use_amp: bool,
) -> tuple[float, float]:
    """Run one training epoch.

    Returns:
        (mean_loss, accuracy) over all batches.
    """
    model.train()
    total_loss = 0.0
    correct = 0
    total = 0
    t0 = time.perf_counter()

    for batch_idx, (images, labels) in enumerate(loader):
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.amp.autocast('cuda', enabled=use_amp):
            logits = model(images)
            loss = criterion(logits, labels)

        scaled_loss = scaler.scale(loss)
        assert isinstance(scaled_loss, torch.Tensor)
        scaled_loss.backward()
        scaler.step(optimizer)
        scaler.update()

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += images.size(0)

    elapsed = time.perf_counter() - t0
    imgs_per_sec = total / elapsed
    mean_loss = total_loss / total
    accuracy = correct / total
    log.info(
        "Epoch %d TRAIN | loss=%.4f acc=%.4f | %.0f img/s",
        epoch, mean_loss, accuracy, imgs_per_sec,
    )
    return mean_loss, accuracy


@torch.no_grad()
def validate(
    model: nn.Module,
    loader: DataLoader,  # type: ignore[type-arg]
    criterion: nn.Module,
    device: torch.device,
    epoch: int,
    use_amp: bool,
) -> tuple[float, float, float, list[int], list[int]]:
    """Run validation.

    Returns:
        (mean_loss, accuracy, macro_f1, all_targets, all_preds)
    """
    model.eval()
    total_loss = 0.0
    correct = 0
    total = 0
    all_targets: list[int] = []
    all_preds: list[int] = []

    for images, labels in loader:
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        with torch.amp.autocast('cuda', enabled=use_amp):
            logits = model(images)
            loss = criterion(logits, labels)

        total_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += images.size(0)
        all_targets.extend(labels.cpu().tolist())
        all_preds.extend(preds.cpu().tolist())

    mean_loss = total_loss / total
    accuracy = correct / total
    macro_f1: float = f1_score(all_targets, all_preds, average="macro", zero_division=0)

    log.info(
        "Epoch %d VAL   | loss=%.4f acc=%.4f macro_f1=%.4f",
        epoch, mean_loss, accuracy, macro_f1,
    )
    return mean_loss, accuracy, macro_f1, all_targets, all_preds


# ---------------------------------------------------------------------------
# Main training entry point
# ---------------------------------------------------------------------------

def train(cfg: dict) -> None:  # type: ignore[type-arg]
    """Full training run controlled by the config dict."""

    # ---- Reproducibility -------------------------------------------------
    seed: int = cfg.get("seed", 42)
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)  # albumentations p= gates use Python's stdlib random

    # ---- Device ----------------------------------------------------------
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    log.info("Using device: %s", device)

    # ---- Backbone / model ------------------------------------------------
    backbone_name: str = cfg["backbone"]
    num_classes: int = cfg.get("num_classes", NUM_CLASSES)
    assert num_classes == NUM_CLASSES, (
        f"num_classes in config ({num_classes}) != NUM_CLASSES ({NUM_CLASSES}). "
        "This project is 8-way single-softmax; do not change num_classes."
    )

    log.info("Building model: %s (pretrained=%s)", backbone_name, cfg.get("pretrained", True))
    model = build_model(
        backbone_name=backbone_name,
        num_classes=num_classes,
        pretrained=cfg.get("pretrained", True),
    )
    model = model.to(device)

    # ---- Image size & transforms ----------------------------------------
    img_size: int = cfg.get("image_size", 224)
    log.info("Image size: %dx%d", img_size, img_size)

    normalize_mean: tuple[float, ...] = tuple(cfg.get("normalize_mean", [0.485, 0.456, 0.406]))
    normalize_std: tuple[float, ...] = tuple(cfg.get("normalize_std", [0.229, 0.224, 0.225]))

    # ---- Datasets & DataLoaders ------------------------------------------
    train_dataset = FocalPlanesDataset(
        csv_path=cfg["train_csv"],
        transform=get_train_transform(img_size=img_size, mean=normalize_mean, std=normalize_std),
    )
    val_dataset = FocalPlanesDataset(
        csv_path=cfg["val_csv"],
        transform=get_eval_transform(img_size=img_size, mean=normalize_mean, std=normalize_std),
    )

    num_workers: int = cfg.get("num_workers", 4)
    batch_size: int = cfg.get("batch_size", 32)

    train_loader: DataLoader = DataLoader(  # type: ignore[type-arg]
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=True,
        persistent_workers=(num_workers > 0),
    )
    val_loader: DataLoader = DataLoader(  # type: ignore[type-arg]
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
        persistent_workers=(num_workers > 0),
    )

    # ---- Loss function ---------------------------------------------------
    weight_tensor = build_class_weight_tensor(cfg["class_weights_json"], device)
    loss_fn_name: str = cfg.get("loss_fn", "ce").lower()
    if loss_fn_name == "focal":
        focal_gamma: float = float(cfg.get("focal_gamma", 2.0))
        criterion: nn.Module = FocalLoss(weight=weight_tensor, gamma=focal_gamma)
        log.info("Loss: FocalLoss (gamma=%.1f, class-weighted)", focal_gamma)
    else:
        criterion = nn.CrossEntropyLoss(weight=weight_tensor)
        log.info("Loss: CrossEntropyLoss (class-weighted)")

    # ---- Optimizer + scheduler -------------------------------------------
    lr: float = float(cfg.get("lr", 3e-4))
    weight_decay: float = float(cfg.get("weight_decay", 0.01))
    epochs_max: int = cfg.get("epochs_max", 60)

    optimizer = AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)

    scheduler_name: str = cfg.get("scheduler", "cosine")
    if scheduler_name == "cosine":
        scheduler: torch.optim.lr_scheduler.LRScheduler = CosineAnnealingLR(
            optimizer, T_max=epochs_max, eta_min=lr * 0.01
        )
    else:
        # Step decay fallback: decay by 0.1 every 20 epochs
        scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=20, gamma=0.1)

    # ---- AMP scaler ------------------------------------------------------
    use_amp: bool = cfg.get("amp", True) and device.type == "cuda"
    scaler = torch.amp.GradScaler('cuda', enabled=use_amp)

    # ---- TensorBoard writer ----------------------------------------------
    log_dir = Path(cfg.get("log_dir", f"logs/{backbone_name}"))
    log_dir.mkdir(parents=True, exist_ok=True)
    writer = SummaryWriter(log_dir=str(log_dir))

    # ---- Checkpoint dir --------------------------------------------------
    ckpt_dir = Path(cfg.get("checkpoint_dir", f"checkpoints/{backbone_name}"))
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    # ---- Early stopping state -------------------------------------------
    patience: int = cfg.get("early_stopping_patience", 8)
    best_macro_f1: float = -1.0
    epochs_without_improvement: int = 0
    best_epoch: int = 0

    # ---- Training loop ---------------------------------------------------
    log.info(
        "Starting training: backbone=%s, epochs_max=%d, patience=%d, lr=%.2e, amp=%s",
        backbone_name, epochs_max, patience, lr, use_amp,
    )

    for epoch in range(1, epochs_max + 1):
        t_epoch_start = time.perf_counter()

        # --- Train ---
        train_loss, train_acc = train_one_epoch(
            model, train_loader, criterion, optimizer, scaler, device, epoch, use_amp
        )

        # --- Validate ---
        val_loss, val_acc, val_macro_f1, val_targets, val_preds = validate(
            model, val_loader, criterion, device, epoch, use_amp
        )

        # --- Scheduler step ---
        current_lr: float = optimizer.param_groups[0]["lr"]
        scheduler.step()

        # --- Per-class F1 (log every epoch) ---
        per_class_f1: np.ndarray = f1_score(
            val_targets, val_preds,
            average=None,  # type: ignore[arg-type]
            labels=list(range(NUM_CLASSES)),
            zero_division=0,
        )

        # --- TensorBoard logging ---
        epoch_time = time.perf_counter() - t_epoch_start
        imgs_per_sec = (len(train_dataset) + len(val_dataset)) / epoch_time

        writer.add_scalar("Loss/train", train_loss, epoch)
        writer.add_scalar("Loss/val", val_loss, epoch)
        writer.add_scalar("Accuracy/train", train_acc, epoch)
        writer.add_scalar("Accuracy/val", val_acc, epoch)
        writer.add_scalar("MacroF1/val", val_macro_f1, epoch)
        writer.add_scalar("LR", current_lr, epoch)
        writer.add_scalar("Throughput/imgs_per_sec", imgs_per_sec, epoch)

        for cls_name, cls_f1 in zip(CANONICAL_CLASSES, per_class_f1.tolist()):
            writer.add_scalar(f"PerClassF1/{cls_name}", cls_f1, epoch)

        # --- Best checkpoint ---
        if val_macro_f1 > best_macro_f1:
            best_macro_f1 = val_macro_f1
            best_epoch = epoch
            epochs_without_improvement = 0

            best_ckpt_path = ckpt_dir / "best.pt"
            torch.save(
                {
                    "epoch": epoch,
                    "backbone": backbone_name,
                    "val_macro_f1": val_macro_f1,
                    "model_state_dict": model.state_dict(),
                    "optimizer_state_dict": optimizer.state_dict(),
                    "config": cfg,
                },
                str(best_ckpt_path),
            )
            log.info(
                "✓ New best checkpoint (val macro-F1=%.4f) → %s",
                best_macro_f1, best_ckpt_path,
            )

            # Save confusion matrix at best epoch
            cm_path = ckpt_dir / f"confusion_matrix_best_epoch{epoch}.png"
            save_confusion_matrix(val_targets, val_preds, cm_path, epoch)

        else:
            epochs_without_improvement += 1
            log.info(
                "No improvement for %d/%d epochs (best=%.4f @ epoch %d)",
                epochs_without_improvement, patience, best_macro_f1, best_epoch,
            )

        # --- Early stopping ---
        if epochs_without_improvement >= patience:
            log.info(
                "Early stopping triggered after %d epochs without improvement.",
                patience,
            )
            break

    # ---- Final epoch artefacts ------------------------------------------
    log.info(
        "Training complete. Best val macro-F1=%.4f at epoch %d.",
        best_macro_f1, best_epoch,
    )

    # Reload best.pt before generating the final report
    best_ckpt_path = ckpt_dir / "best.pt"
    if best_ckpt_path.exists():
        log.info("Reloading best checkpoint (epoch %d, macro_f1=%.4f) for final report", best_epoch, best_macro_f1)
        best_state = torch.load(str(best_ckpt_path), map_location=device, weights_only=False)
        model.load_state_dict(best_state["model_state_dict"])
        val_loss, val_acc, val_macro_f1, val_targets, val_preds = validate(
            model, val_loader, criterion, device, best_epoch, use_amp
        )

    cm_final_path = ckpt_dir / f"confusion_matrix_final_epoch{best_epoch}.png"
    save_confusion_matrix(val_targets, val_preds, cm_final_path, best_epoch)

    # Save per-class classification report to text file
    report_path = ckpt_dir / "classification_report_final.txt"
    report = classification_report(
        val_targets, val_preds,
        target_names=CANONICAL_CLASSES,
        zero_division=0,
    )
    report_path.write_text(report, encoding="utf-8")
    log.info("Classification report → %s", report_path)

    writer.close()
    log.info("TensorBoard logs → %s", log_dir)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a fetal plane classifier (8-way softmax)."
    )
    parser.add_argument(
        "--config",
        type=str,
        required=True,
        help="Path to a backbone YAML config, e.g. configs/repvgg_a1.yaml",
    )
    parser.add_argument(
        "--epochs-override",
        type=int,
        default=None,
        help="Override epochs_max from config (useful for smoke tests).",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    cfg = load_config(args.config)

    # Apply CLI overrides
    if args.epochs_override is not None:
        cfg["epochs_max"] = args.epochs_override
        log.info("epochs_max overridden to %d via CLI", args.epochs_override)

    # Copy config YAML next to checkpoints for reproducibility (§4.5)
    ckpt_dir = Path(cfg.get("checkpoint_dir", f"checkpoints/{cfg['backbone']}"))
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy(args.config, str(ckpt_dir / "config.yaml"))

    # Setup file logging to ensure UTF-8 output
    log_dir = Path("logs")
    log_dir.mkdir(parents=True, exist_ok=True)
    file_handler = logging.FileHandler(log_dir / f"{cfg['backbone']}_training_output.txt", mode="a", encoding="utf-8")
    file_handler.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s", datefmt="%H:%M:%S"))
    logging.getLogger().addHandler(file_handler)

    train(cfg)
